---
title: "A benchmarking platform for deconvolution methods quantifying cell-type heterogeneity"
output:
  html_document:
    includes:
      in_header: cover.html
---

DECONbench, is a standardized unbiased benchmarking resource, applied to the evaluation of computational methods quantifying cell-type heterogeneity, which is particularly useful in the cancer field. it includes gold standard multi-omic simulated benchmark datasets (transcriptome and methylation data) and a set of baseline deconvolution methods (reference-free algorithms inferring cell-type proportions). DECONbench performs a systematic performance evaluation of each new methodological contribution and provides the possibility to publically share source code and scoring. It allows continuous submission of new methods in a user-friendly fashion, each novel contribution being automatically compared to the reference baseline algorithms, which enables crowdsourcing benchmarking. DECONbench is hosted on the open source Codalab competition platform. 

<font size="4"> 👉Deconbench is freely available [here]( https://competitions.codalab.org/competitions/27453?secret_key=b5ae4e78-8e75-44a4-b919-52907529605c). </font> 

  

How to cite  
DECONbench: a benchmarking platform dedicated to deconvolution methods for tumor heterogeneity quantification. C. Decamps, et al., bioRxiv 2020.06.06.131482;  doi: 10.1101/2020.06.06.131482

